workflows:
  ios-release:
    name: FoodMali iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
