// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQFfMbdVgvRyEMbY12UsEPU7e3XfuNhM',
    appId: '1:363472131073:web:9e2d3a8d170ed748fb9c00',
    messagingSenderId: '363472131073',
    projectId: 'foodmali',
    authDomain: 'foodmali.firebaseapp.com',
    storageBucket: 'foodmali.firebasestorage.app',
    measurementId: 'G-NYHJ991X66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l2YlYWi5221yMbmdGERQ9hRGtSnxeKs',
    appId: '1:363472131073:android:e40f543fb368f3f1fb9c00',
    messagingSenderId: '363472131073',
    projectId: 'foodmali',
    storageBucket: 'foodmali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaE_U3EEPYuXnQLimIaylCnclvt8tZn3k',
    appId: '1:363472131073:ios:2d0a4d0cb0bb1e1dfb9c00',
    messagingSenderId: '363472131073',
    projectId: 'foodmali',
    storageBucket: 'foodmali.firebasestorage.app',
    iosBundleId: 'com.lawoldev.foodmali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaE_U3EEPYuXnQLimIaylCnclvt8tZn3k',
    appId: '1:363472131073:ios:2ed946f89a50943afb9c00',
    messagingSenderId: '363472131073',
    projectId: 'foodmali',
    storageBucket: 'foodmali.firebasestorage.app',
    iosBundleId: 'com.lawoldev.foodMali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFQFfMbdVgvRyEMbY12UsEPU7e3XfuNhM',
    appId: '1:363472131073:web:f3c86f60c5cc0ac1fb9c00',
    messagingSenderId: '363472131073',
    projectId: 'foodmali',
    authDomain: 'foodmali.firebaseapp.com',
    storageBucket: 'foodmali.firebasestorage.app',
    measurementId: 'G-67G3FHGQK8',
  );

}